### ISSUE TITLE
[EPIC] Review framework.dev sites for potential improvements

### ISSUE THREAD

**Issue by Atrophius** [thisdot/framework.dev#683]
The goal of this ticket is to generate additional tickets with improvements to the framework.dev sites. Get really nitpicky with this review, very fine-tooth comb-like. If you see anything that looks odd, out of place, or confusing let's get it cleaned up. Poor image quality, missing images, text that is unclear, design that doesn't look quite right, anything is on the table.

New Issues:

- [x] https://github.com/thisdot/framework.dev/issues/691
- [x] https://github.com/thisdot/framework.dev/issues/710
- [x] https://github.com/thisdot/framework.dev/issues/711
- [x] https://github.com/thisdot/framework.dev/issues/712
- [x] https://github.com/thisdot/framework.dev/issues/713
- [x] https://github.com/thisdot/framework.dev/issues/714
- [x] https://github.com/thisdot/framework.dev/issues/715
- [x] https://github.com/thisdot/framework.dev/issues/716
- [x] https://github.com/thisdot/framework.dev/issues/717
- [x] https://github.com/thisdot/framework.dev/issues/718
- [x] https://github.com/thisdot/framework.dev/issues/719
- [x] https://github.com/thisdot/framework.dev/issues/720
- [x] https://github.com/thisdot/framework.dev/issues/721
- [x] https://github.com/thisdot/framework.dev/issues/722
- [x] https://github.com/thisdot/framework.dev/issues/723
- [x] https://github.com/thisdot/framework.dev/issues/724
- [x] https://github.com/thisdot/framework.dev/issues/725
